import { Router } from "express";
import authRoutes from "./modules/auth/routes";
import userRoutes from "./modules/users/routes";
import categoryRoutes from "./modules/categories/routes";
import adRoutes from "./modules/ads/routes";
import uploadRoutes from "./modules/uploads/routes";
import adminRoutes from "./modules/admin/routes";
import conversationRoutes from "./modules/conversations/routes";
import messageRoutes from "./modules/messages/routes";
import notificationRoutes from "./modules/notifications/routes";
import verificationRoutes from "./modules/verification/routes";
import paymentRoutes from "./modules/payments/routes";
import seoRoutes from "./modules/seo/routes";
import { createRateLimiter } from "./middleware/rateLimit";

const router = Router();
const globalRateLimit = createRateLimiter({ keyPrefix: "global", windowMs: 15 * 60_000, max: 200 });
const authRateLimit = createRateLimiter({ keyPrefix: "auth", windowMs: 15 * 60_000, max: 50 });
const uploadRateLimit = createRateLimiter({ keyPrefix: "uploads", windowMs: 15 * 60_000, max: 30 });
const messageRateLimit = createRateLimiter({ keyPrefix: "messages", windowMs: 60_000, max: 60 });

router.get("/health", (_req, res) => res.json({ success: true, data: { status: "ok" }, message: "Qwik API is running" }));
router.use(globalRateLimit);
router.use("/auth", authRateLimit, authRoutes);
router.use("/users", userRoutes);
router.use("/categories", categoryRoutes);
router.use("/ads", adRoutes);
router.use("/uploads", uploadRateLimit, uploadRoutes);
router.use("/admin", adminRoutes);
router.use("/conversations", messageRateLimit, conversationRoutes);
router.use("/messages", messageRateLimit, messageRoutes);
router.use("/notifications", notificationRoutes);
router.use("/verification", verificationRoutes);
router.use("/payments", paymentRoutes);
router.use("/", seoRoutes);
export default router;
